{
 "title": "EKL Overview Per Environment",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": "ekl-backend-ws-dev,ekl-backend-ws-test"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div class=\"dashboard-header\" style=\"text-align:center\"><h1>EKL Backend Application Overview </h1></div>"
   }
  },
  { "title": "Application Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 8, "x": 5, "y": 3 },
   "options": {
    "content": "<table style=\"width:100%\">\n  <tr><td>Environment</td><td>ekl-dev</td></tr>\n  <tr><td>Github Repository</td><td><a href=\"https://github.com/yiyu-qiao/ekl-backend-parent.git\">ekl-backend-parent</a></td></tr>\n  <tr><td>Owned by</td><td><a href=\"https://github.com/qiaohanscode\">Qiao Han</a>\n                      <br><a href=\"https://github.com/yiyuma\">Yiyu Ma</a></td></tr>\n  <tr><td>Platform</td><td>kubernetes<br>1.29</td></tr>\n  <tr><td>Jenkins</td><td><a href=\"https://ekl-jenkins.ponyworld.io\">ekl-jenkins.ponyworld.io</a></td></tr>\n</table>"
   }
  },
  {
   "title": "Application description",
   "type": "text",
   "gridPos": { "h": 6, "w": 9, "x": 14, "y": 3 },
   "options": {
    "content": "\n#### EKL is a web application consisting of two components,\n- ekl frontend -- is the Web UI of EKL which is available under [ekl-dev.ponyworld.io](https://ekl-dev.ponyworld.io) \n- ekl backend -- is based on Spring Boot and provides the Web Services of EKL."
   }
  },
  { "title": "Basic Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CN=ekl-k8s-dev expires On",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_ssl_last_chain_expiry_timestamp_seconds{instance=\"https://ekl-dev.ponyworld.io\", job=\"blackbox-ekl-dev\"}*1000",
     "legendFormat": "expires"
    }
   ]
  },
  {
   "title": "CN=ekl-k8s-dev expires On",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_ssl_last_chain_expiry_timestamp_seconds{instance=\"https://ekl-dev.ponyworld.io\", job=\"blackbox-ekl-dev\"} - time()",
     "legendFormat": "expires"
    }
   ]
  },
  {
   "title": "Health $application",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 14 },
   "repeat": "application",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(min_over_time(up{app=\"$application\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime $application",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 14 },
   "repeat": "application",
   "targets": [
    {
     "expr": "process_uptime_seconds{app=\"$application\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}