{
 "title": "EKL Backend WS",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": "ekl-backend-ws-dev,ekl-backend-ws-test"
   },
   {
    "name": "kubernetes_pod_name",
    "label": "kubernetes_pod_name",
    "query": {
     "query": "query_result(rate(up{app=\"ekl-backend-ws-dev\"}[$__range]))"
    }
   },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": {
     "query": "query_result(rate(jvm_memory_max_bytes{app=\"$application\", area=\"heap\"}[$__range]))"
    }
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": {
     "query": "query_result(jvm_memory_used_bytes{app=\"$application\", area=\"nonheap\"})"
    }
   },
   {
    "name": "hikaricp",
    "label": "HikariCP-Pool",
    "query": {
     "query": "query_result(hikaricp_connections{app=\"$application\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div class=\"dashboard-header\" style=\"text-align:center\"><h1>EKL Backend WS</h1></div>"
   }
  },
  { "title": "Application Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 8, "x": 5, "y": 3 },
   "options": {
    "content": "<table style=\"width:100%\">\n  <tr><td>Environment</td><td>ekl-dev</td></tr>\n  <tr><td>Github Repository</td><td><a href=\"https://github.com/yiyu-qiao/ekl-backend-parent.git\">ekl-backend-parent</a></td></tr>\n  <tr><td>Owned by</td><td><a href=\"https://github.com/qiaohanscode\">Qiao Han</a>\n                      <br><a href=\"https://github.com/yiyuma\">Yiyu Ma</a></td></tr>\n  <tr><td>Platform</td><td>kubernetes<br>1.29</td></tr>\n  <tr><td>Jenkins</td><td><a href=\"https://ekl-jenkins.ponyworld.io\">ekl-jenkins.ponyworld.io</a></td></tr>\n</table>"
   }
  },
  {
   "title": "Application description",
   "type": "text",
   "gridPos": { "h": 6, "w": 9, "x": 14, "y": 3 },
   "options": {
    "content": "\n#### EKL is a web application consisting of two components,\n- ekl frontend -- is the Web UI of EKL which is available under [ekl-dev.ponyworld.io](https://ekl-dev.ponyworld.io) \n- ekl backend -- is based on Spring Boot and provides the Web Services of EKL."
   }
  },
  { "title": "Basic Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{pod=\"$kubernetes_pod_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\", pod=\"$kubernetes_pod_name\"})*100/sum(jvm_memory_max_bytes{area=\"heap\",pod=\"$kubernetes_pod_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"nonheap\",pod=\"$kubernetes_pod_name\"})/sum(jvm_memory_max_bytes{area=\"nonheap\",pod=\"$kubernetes_pod_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process CPU",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{pod=\"$kubernetes_pod_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System CPU",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_usage{pod=\"$kubernetes_pod_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tomcat Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tomcat_threads_current_threads{pod=\"$kubernetes_pod_name\"}",
     "legendFormat": "current"
    },
    {
     "expr": "tomcat_threads_busy_threads{pod=\"$kubernetes_pod_name\"}",
     "legendFormat": "busy"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{pod=\"$kubernetes_pod_name\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_cpu_usage{pod=\"$kubernetes_pod_name\"}",
     "legendFormat": "Process CPU Usage"
    },
    {
     "expr": "system_cpu_usage{pod=\"$kubernetes_pod_name\"}",
     "legendFormat": "System CPU Usage"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load_average_1m{pod=\"$kubernetes_pod_name\"}",
     "legendFormat": "Load Average [1m]"
    },
    {
     "expr": "system_cpu_count{pod=\"$kubernetes_pod_name\"}",
     "legendFormat": "CPU Core Size"
    }
   ]
  },
  {
   "title": "Tomcat Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "targets": [
    {
     "expr": "tomcat_connections_current_connections{pod=\"$kubernetes_pod_name\"}",
     "legendFormat": "current"
    },
    {
     "expr": "tomcat_connections_keepalive_current_connections{pod=\"$kubernetes_pod_name\"}",
     "legendFormat": "keep alive"
    }
   ]
  },
  {
   "title": "Taskes Queued/Completed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (name)(irate(executor_completed_tasks_total{pod=\"$kubernetes_pod_name\"}[2m]))",
     "legendFormat": "Complete({{name}})"
    },
    {
     "expr": "sum by (name)(irate(executor_queued_tasks{pod=\"$kubernetes_pod_name\"}[2m]))",
     "legendFormat": "Queued({{name}})"
    }
   ]
  },
  {
   "title": "Executors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "executor_active_threads{pod=\"$kubernetes_pod_name\"}",
     "legendFormat": "Active({{pod}})"
    },
    {
     "expr": "executor_pool_core_threads{pod=\"$kubernetes_pod_name\"}",
     "legendFormat": "Core Pool({{pod}})"
    }
   ]
  },
  {
   "title": "Process Open Files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "targets": [
    {
     "expr": "process_files_open_files{pod=\"$kubernetes_pod_name\"}",
     "legendFormat": "process_files_open_files"
    }
   ]
  },
  { "title": "JVM Statistics - Memeory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "$memory_pool_heap (heap)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "repeat": "memory_pool_heap",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{id=\"$memory_pool_heap\",pod=\"$kubernetes_pod_name\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{id=\"$memory_pool_heap\",pod=\"$kubernetes_pod_name\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{id=\"$memory_pool_heap\",pod=\"$kubernetes_pod_name\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "$memory_pool_nonheap (non-heap)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 43 },
   "repeat": "memory_pool_nonheap",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{id=\"${memory_pool_nonheap:raw}\", pod=\"$kubernetes_pod_name\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{id=\"${memory_pool_nonheap:raw}\", pod=\"$kubernetes_pod_name\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{id=\"${memory_pool_nonheap:raw}\", pod=\"$kubernetes_pod_name\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Classes Loaded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{pod=\"$kubernetes_pod_name\"}",
     "legendFormat": "Classes Loaded"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{id=\"direct\", pod=\"$kubernetes_pod_name\"}",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{id=\"direct\", pod=\"$kubernetes_pod_name\"}",
     "legendFormat": "Capacity Bytes"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{id=\"mapped\", pod=\"$kubernetes_pod_name\"}",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{id=\"mapped\", pod=\"$kubernetes_pod_name\"}",
     "legendFormat": "Capacity Bytes"
    }
   ]
  },
  {
   "title": "Mapped - 'non-volatile memory' Buffers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{id=\"mapped - 'non-volatile memory'\", pod=\"$kubernetes_pod_name\"}",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{id=\"mapped - 'non-volatile memory'\", pod=\"$kubernetes_pod_name\"}",
     "legendFormat": "Capacity Bytes"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_daemon_threads{pod=\"$kubernetes_pod_name\"}",
     "legendFormat": "Daemon"
    },
    {
     "expr": "jvm_threads_live_threads{pod=\"$kubernetes_pod_name\"}",
     "legendFormat": "Live"
    },
    {
     "expr": "jvm_threads_peak_threads{pod=\"$kubernetes_pod_name\"}",
     "legendFormat": "Peak"
    }
   ]
  },
  {
   "title": "Memory Allocated/Promote",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(jvm_gc_memory_allocated_bytes_total{pod=\"$kubernetes_pod_name\"}[5m])",
     "legendFormat": "Daemon"
    }
   ]
  },
  { "title": "JVM Statistics - GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "GC Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_count{pod=\"$kubernetes_pod_name\"}[5m])",
     "legendFormat": "{{action}}[{{cause}}]"
    }
   ]
  },
  {
   "title": "GC Stop the World Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_sum{pod=\"$kubernetes_pod_name\"}[5m])",
     "legendFormat": "{{action}}[{{cause}}]"
    }
   ]
  },
  { "title": "HikariCP Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Connections Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections{app=\"$application\", pool=\"$hikaricp\", pod=\"$kubernetes_pod_name\"}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hikaricp_connections{app=\"$application\", pool=\"$hikaricp\", pod=\"$kubernetes_pod_name\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "hikaricp_connections_idle{app=\"$application\", pool=\"$hikaricp\", pod=\"$kubernetes_pod_name\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "hikaricp_connections_pending{app=\"$application\", pool=\"$hikaricp\", pod=\"$kubernetes_pod_name\"}",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Connections Timeout Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_timeout_total{app=\"$application\", pool=\"$hikaricp\", pod=\"$kubernetes_pod_name\"}"
    }
   ]
  },
  {
   "title": "Connection Creation Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hikaricp_connections_creation_seconds_sum{app=\"$application\", pool=\"$hikaricp\", pod=\"$kubernetes_pod_name\"}/hikaricp_connections_creation_seconds_count{app=\"$application\", pool=\"$hikaricp\", pod=\"$kubernetes_pod_name\"}",
     "legendFormat": "Creation time"
    }
   ]
  },
  {
   "title": "Connection Usage Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hikaricp_connections_usage_seconds_sum{app=\"$application\", pool=\"$hikaricp\", pod=\"$kubernetes_pod_name\"}/hikaricp_connections_usage_seconds_count{app=\"$application\", pool=\"$hikaricp\", pod=\"$kubernetes_pod_name\"}",
     "legendFormat": "Usage time"
    }
   ]
  },
  {
   "title": "Connection Acquire Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hikaricp_connections_acquire_seconds_sum{app=\"$application\", pool=\"$hikaricp\", pod=\"$kubernetes_pod_name\"}/hikaricp_connections_acquire_seconds_count{app=\"$application\", pool=\"$hikaricp\", pod=\"$kubernetes_pod_name\"}",
     "legendFormat": "Acquire time"
    }
   ]
  },
  { "title": "HTTP Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{pod=\"$kubernetes_pod_name\"}[10m])",
     "legendFormat": "{{uri}}:{{method}} [{{status}}]"
    }
   ]
  },
  {
   "title": "Request Count Status 2xx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{pod=\"$kubernetes_pod_name\", status=~\"2..\"}[10m])",
     "legendFormat": "{{uri}}:{{method}} [{{status}}]"
    }
   ]
  },
  {
   "title": "Request Count Status 4xx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{pod=\"$kubernetes_pod_name\", status=~\"^4..\"}[10m])",
     "legendFormat": "{{uri}}:{{method}} [{{status}}]"
    }
   ]
  },
  {
   "title": "Request Count Status 5xx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{pod=\"$kubernetes_pod_name\", status=~\"^5..\"}[10m])",
     "legendFormat": "{{uri}}:{{method}} [{{status}}]"
    }
   ]
  },
  { "title": "Logback Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "ERROR logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(logback_events_total{level=\"error\", pod=\"$kubernetes_pod_name\"}[5m])",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "WARN logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(logback_events_total{level=\"warn\", pod=\"$kubernetes_pod_name\"}[5m])",
     "legendFormat": "warn"
    }
   ]
  },
  {
   "title": "LOGS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(logback_events_total{pod=\"$kubernetes_pod_name\"}[5m])",
     "legendFormat": "{{level}}"
    }
   ]
  }
 ]
}